### ISSUE TITLE
Generate 2 plots, using Hu-moments and Hausdorff Distance

### ISSUE THREAD

**Issue by pinakinathc** [pinakinathc/shapeAnalyzer#7]
in PR #2 Hu-moments was removed from **main.py** and instead we used Hausdroff distance.
We need to generate 2 plots:
* One plot where the similarity is calculated using Hu-moments
* Another plot where the similarity is calculated using Hausdroff Distance

**Comment by NamrataGuptaRoy** [comment]
I am working on this issue.
